name: health
description: Wrapper for the iOS HealthKit and Android GoogleFit services.
version: 4.1.0
homepage: https://github.com/ketanchoyal/health

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1
  device_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: cachet.plugins.health
        pluginClass: HealthPlugin
      ios:
        pluginClass: HealthPlugin
